### ISSUE TITLE
TIPP10 readme on custom layout

### ISSUE THREAD

**Issue by deekayen** [binaryphile/minimak#5]
Re: http://www.minimak.org/learn/

"The best program I’ve found to use this word list is the free, cross-platform TIPP10 typing tutor. There are instructions in the README on how to add these word lists as lessons."

Which README where? I've been unable to figure how to add a custom layout to TIPP10.

**Comment by binaryphile** [comment]
Sorry, poorly worded.  It's the readme in the words directory.  I'll try to improve the text.

**Comment by binaryphile** [comment]
Fixed on the site.
