### ISSUE TITLE
Capslock on non-capslock layouts reverts to QWERTY on Mac

### ISSUE THREAD

**Issue by babakness** [binaryphile/minimak#8]
Hello--I noticed a bug or unpleasant feature: trying to use the capslock on Minimak-4 (the one that retains capslock functionality) on a Mac causes all keys to revert to  QWERTY!

**Comment by binaryphile** [comment]
Thanks for logging the issue.

Unfortunately, the Mac mappings were donated to me and I don't have a Mac on which to test.  Perhaps @fullybaked can help diagnose the issue, he's the one who developed Minimak on the Mac.  His profile is at: https://github.com/fullybaked.

**Comment by fullybaked** [comment]
I've modified the OSX bindings and sent a pull request.  Sorry for missing them out, as mentioned in the PR I have caps lock bound to something else and never use it so it didn't cross my mind to test

**Comment by binaryphile** [comment]
I should get around to putting out a new zip on the site in a day or two, but @babakness you can grab his updates from here since they're merged in the latest master.

I'm closing this issue.  Ping me if it rears its head again in any way.
